CREATE DATABASE bdFiliados_PTC
USE bdFiliados_PTC
SELECT * FROM dbo.Filiados_PTC

--1
SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'

--2
SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'SEBASTIÃO%'

--3
SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE '%OS'

--4
SELECT NOME_DO_FILIADO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO = 'São Félix'

--5
SELECT NOME_DO_FILIADO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'Inhambupe%'

--6
SELECT NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'Santa%'

--7
SELECT NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE 'E%'

--8 
SELECT NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE '%Cruz%'

--9
SELECT NOME_DO_MUNICIPIO FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO LIKE '%De%'

--10
SELECT * FROM dbo.Filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '01/01/1990' AND '01/01/2000'

--11
SELECT * FROM dbo.Filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010' AND '01/03/2010'

--12
SELECT * FROM dbo.Filiados_PTC
WHERE DATA_DA_FILIACAO BETWEEN '01/06/2007' AND '31/12/2007'

--13
SELECT * FROM dbo.Filiados_PTC
WHERE SITUACAO_DO_REGISTRO LIKE 'REGULAR%'

--14
SELECT * FROM dbo.Filiados_PTC
WHERE ZONA_ELEITORAL LIKE '203%'

--15
SELECT * FROM dbo.Filiados_PTC
WHERE ZONA_ELEITORAL LIKE '180%'

--16
SELECT * FROM dbo.Filiados_PTC
WHERE ZONA_ELEITORAL LIKE '199%'

--17
SELECT MAX(CODIGO_DO_MUNICIPIO) FROM dbo.Filiados_PTC

--18
SELECT MIN(CODIGO_DO_MUNICIPIO) FROM dbo.Filiados_PTC

--19
UPDATE  dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PT'
WHERE CODIGO_DO_MUNICIPIO = 36471

SELECT * FROM dbo.Filiados_PTC
WHERE CODIGO_DO_MUNICIPIO = 36471

--20
UPDATE  dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PMDB'
WHERE CODIGO_DO_MUNICIPIO = '38490'

SELECT * FROM dbo.Filiados_PTC
WHERE CODIGO_DO_MUNICIPIO = '38490'

--21
UPDATE  dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PC'
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS'

--22
UPDATE  dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PV', NOME_DO_PARTIDO = 'Partido Verde'
WHERE NOME_DO_MUNICIPIO = 'São Félix'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO = 'São Félix'

--23
UPDATE  dbo.Filiados_PTC
SET SIGLA_DO_PARTIDO ='PSDB', NOME_DO_PARTIDO = 'Partido da Social Democracia Brasileira'
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

--24
UPDATE  dbo.Filiados_PTC
SET NOME_DO_FILIADO ='JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NOME_DO_FILIADO LIKE 'JORGE LUIS FERREIRA DOS SANTOS%'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'JORGE LUIS MAGALHÃES DOS SANTOS%'

--25
UPDATE  dbo.Filiados_PTC
SET NOME_DO_FILIADO ='RENATA XAVIER RODRIGUES'
WHERE NOME_DO_FILIADO LIKE 'BENTA XAVIER RODRIGUES%'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'RENATA XAVIER RODRIGUES%'

--26
UPDATE  dbo.Filiados_PTC
SET NOME_DO_FILIADO ='NOEL LEITE DA SILVA'
WHERE NOME_DO_FILIADO LIKE 'NOE LEITE DA SILVA%'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'NOEL LEITE DA SILVA%'

--27
UPDATE  dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO ='REGULAR'
WHERE NOME_DO_FILIADO LIKE 'JOSIENE ANDRADE DE SOUZA%'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'JOSIENE ANDRADE DE SOUZA%'

--28
UPDATE  dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO ='REGULAR'
WHERE NOME_DO_FILIADO LIKE 'ELIEL ALMEIDA SILVA%'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'ELIEL ALMEIDA SILVA%'

--29
UPDATE  dbo.Filiados_PTC
SET SITUACAO_DO_REGISTRO ='DESFILIADO'
WHERE NOME_DO_FILIADO LIKE 'ALINE DE SOUZA%'

SELECT * FROM dbo.Filiados_PTC
WHERE NOME_DO_FILIADO LIKE 'ALINE DE SOUZA%'

--30
ALTER TABLE dbo.Filiados_PTC
ADD SEXO CHAR(10)








